### ISSUE TITLE
[Performance] remove ~ notation

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/state#25]
will convert subs objects to hash tables -- slows down performance of looping

perhaps we can use `$root` or `$`

```{ $: { james: true } }``` only $ resonates with the reference notation

```{ $root: { james: true } }``` clearer to read

**Comment by jimdebeer** [comment]
currently in favour of `$`

**Comment by nikoloza** [comment]
I also like `$`, but to make it more clear we can use `$root` and `$subscribe` maybe? No one will be confused.

**Comment by jimdebeer** [comment]
@nfrade what do you think?

**Comment by nfrade** [comment]
I think we should be as explicit as possible. $ is too generic. I was confused about it's meaning when I looked at it.
On the other hand if we see $something it's clear it's an system/namespaced symbol.

**Comment by jimdebeer** [comment]
what about just root ?

**Comment by nikoloza** [comment]
I think root can easily be element name. Or we can make it reserved. not sure if it's good idea

**Comment by nikoloza** [comment]
@jimdebeer we use $$ for subscribe and $ for root

**Comment by nfrade** [comment]
Well we're working on a very flexible object structure. It can be overwhelming and confusing because you don't know what is custom and what belongs to the framework. I noticed that a lot when first looked at the project.
My opinion is everything that belongs to the framework should be namespaced (and I just mean have a prefix on it) and explicit.
For example: how do I know if "root" is an element/key that I/someone created vs a feature?

**Comment by jimdebeer** [comment]
its is decided` $root` and `$parent` (note this is only in subscriptions!)

**Comment by jimdebeer** [comment]
for the element stuff lets make an issue there to see how we deal with properties -- we tried to prefix everything and that does not help either (becomes very unclear after too many things)

**Comment by youzi** [comment]
@jimdebeer Shouldn't `parent` just be `parent` since it actually subscribes to `parent`?
